name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target ./package

    # Step 4: Package application for Lambda
    - name: Package application
      run: |
        cp app.py ./package/
        cd package && zip -r ../lambda_function.zip . && cd ..

    # Step 5: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 6: Deploy to AWS Lambda
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name fuzzyneurals \
          --zip-file fileb://fuzzyneurals.zip

